### PR TITLE
minor UI changes and code cleanup

### PR DESCRIPTION
**Pull request by bjesus**
Hey! I love Freetar - it's so incredibly useful! thank you for creating it.

This includes a couple of simple UI changes:
- Use a navbar to make search and darkmode toggle available in every page
- Mark favorites on search results too
- Make the Favorites page the homepage
- Replace custom styles (e.g. print.css) with built-in bootstrap styles (e.g. `d-print-none`)
- Allow navigating from chords page to the artist's chords list
- Fix some invalid HTML
- Code formatting

### CODE REVIEW

**Comment by bjesus** [comment]
Also added:
- Replace Font Awesome with unicode (eg. 🌓︎ ★ ) 
- Split the index.html file to index.html and tab.html
- Evaluate dark_mode at the <head> to avoid flickering
- Some mobile adjustments for the tab page

**Comment by kmille** [comment]
Hey, thanks for the PR! I need some time (lot to do right now and want to keep my order of doing things) but I will come back to this later!

**Comment by bjesus** [comment]
Awesome, thank you so much @kmille .

also added above:
- Minifying responses - on my tests this took responses from ~100kb to ~55kb
- Added the ability to export and import favorites (as much as I love localStorage, I want to be make sure I have the data with me...)

**Comment by kmille** [comment]
Hey,

do you have the current main as base or do you need a rebase? I have the following bugs:
- After using the serach: I can not click on the star/fav button (nothing happends)
- Tab view: The show cords button does not work (UPDATE: works on the Smartphone?)
- Tab view: Transpose => I also replaced it with an emoji. It does not do anything if I click on 'Transpose'
	- UPDATE: ah, they are just hidden? On the smartphone, I can see them
- Fav list: removing fav does not work
- Maybe we want to rename Advanced to 'export/import favs'

But else.. it looks much better and I like the new features! I think a upstram rebase fixes some of the problems.

A thing I think it would be nice to improve: On a Smartphone, it needs two clicks to get the search bar. Can you put it always on the top?

Thanks for the contribution and the clean code!

**Comment by bjesus** [comment]
hey, thanks for looking into it!

I've adjusted the mobile navbar to show the search always now, so no need for 2 clicks anymore.

As for clicking the star button in search and on the fav list - this never worked before as far as I can tell? tried it now on https://freetar.androidloves.me/ and it doesn't seem to work either.

Chords button and transposition seem to work fine here. Can you let me know what chords page are you testing with? Some pages aren't working, but again - they're also not working on https://freetar.androidloves.me/ AFAICT.

I was thinking about calling "Advanced" just "Import & Export" but was thinking we might want to put other things there later. not sure - will happily change if you think we should.

**Comment by kmille** [comment]
> I've adjusted the mobile navbar to show the search always now, so no need for 2 clicks anymore.

Looks good. Can you make it a bit bigger for desktop devices? We have space there.

> I was thinking about calling "Advanced" just "Import & Export" but was thinking we might want to put other things there later. not sure - will happily change if you think we should.

You are right, we can keep it as it is.

Does fav/unfav work for you in the list view (search result) right now?

**Comment by bjesus** [comment]
I rewrote the favorites system so it'll work the same across all pages - search results, favorites and the tabs page.
Note that I removed the "?really=True" thing. not sure what it was supposed to do, but since we're matching favorites by URL and not by ID, it makes it harder to match.

**Comment by bjesus** [comment]
I also rewrote the topbar now to center the search bar and make it bigger on desktops

**Comment by kmille** [comment]
Thanks and sorry for the delay! I finally wanted to get this MR merged. 
Can you see the transpose buttons? For me, they are there, but I can't see them (clicking them works, I see them if I hover)
2024-01-24-083017_screenshot
2024-01-24-083020_screenshot

Also, I also use something like [Invidious Redirect](https://addons.mozilla.org/en-US/firefox/addon/invidious-redirection/) as browser extension. It's not yet published/documented. The idea: the button 'show me the site on UG' should then still work and I differ in the web extension with the `really=True`.

**Pull request merged**
