### PR TITLE
Fix build dependencies in Dockerfile (and #9)

### LINKED ISSUE #9: 500 internal server error
These tabs are giving me an internal server error:
- https://freetar.androidloves.me/tab/indigo-girls/closer-to-fine-chords-11115
- https://tabs.ultimate-guitar.com/tab/indigo-girls/closer-to-fine-chords-11115
- https://freetar.androidloves.me/tab/indigo-girls/closer-to-fine-ukulele-3200273
- https://tabs.ultimate-guitar.com/tab/indigo-girls/closer-to-fine-ukulele-3200273

### PR DESCRIPTION
**Pull request by aldahick**
This is a great project! This PR has a couple of small fixes:

- Installs Poetry dependencies in Alpine Dockerfile (`gcc`, `musl-dev`, and `libffi-dev`).
  - Not sure if this was causing problems on amd64 builds, but my image build failed without the dependencies on arm64.
- Fixes #9 by skipping chords without any variants.
  - I didn't see a clear way to still include the chords with empty `variants` lists for the cases mentioned in #9, and skipping them doesn't appear to break anything? The tab loads and looks complete to me.

### CODE REVIEW

**Comment by kmille** [comment]
The Fixes for the  500 internal server looks good. But I don't understand the changes in the Dockerfile. You can only build the Docker image on arm64 with these changes?

**Comment by aldahick** [comment]
Yep, I'm not totally sure why myself. Poetry requires the buildchain packages - maybe the x64 version of the Python image includes them, and not arm64? No clue why that'd be though

**Comment by shruuub** [comment]
> Yep, I'm not totally sure why myself. Poetry requires the buildchain packages - maybe the x64 version of the Python image includes them, and not arm64? No clue why that'd be though

iirc that's how it works (for what ever reason). Also the reason why the x64 package is a tad bit bigger. Thanks for the PR though, works amazingly!

**Comment by kmille** [comment]
Thanks! Merged and released in 0.5.0.

**Pull request merged**
